# Generated by Django 5.1.4 on 2025-02-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='provider',
        ),
    ]
